# Generated by Django 5.1.6 on 2026-05-18 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0003_username_and_url_slugs'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('FACULTY', 'Faculty'), ('STUDENT', 'Student'), ('ADMIN', 'Admin')], default='FACULTY', max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='student_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
