# Generated by Django 5.1.6 on 2026-05-19 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0004_customuser_role_customuser_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_banned',
            field=models.BooleanField(default=False, help_text='Banned users cannot login even if is_active is True.'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('FACULTY', 'Faculty'), ('STUDENT', 'Student')], default='FACULTY', max_length=20),
        ),
    ]
