# Generated by Django 5.1.6 on 2026-05-19 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0005_add_is_banned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('', 'None'), ('FACULTY', 'Faculty'), ('STUDENT', 'Student')], default='FACULTY', max_length=20),
        ),
    ]
