# Generated by Django 5.1.6 on 2026-07-17 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0008_add_account_deletion_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountdeletiontoken',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
