# Generated by Django 6.0.5 on 2026-05-17 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_rebuild_userdetails_public_slugs'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='default_status',
            field=models.TextField(blank=True, default='', help_text='Fallback broadcast message activated when a timed status expires.'),
        ),
    ]
