# Generated by Django 5.1.6 on 2026-05-17 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_userdetails_default_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='is_available',
            field=models.BooleanField(default=False, help_text='Whether the broadcaster is currently available. Toggling to True notifies subscribers.'),
        ),
    ]
