# Generated by Django 5.1.6 on 2026-05-18 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_userdetails_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='default_availability',
            field=models.BooleanField(default=False, help_text='Fallback availability activated when a timed status expires.'),
        ),
    ]
