# Generated by Django 5.1.6 on 2026-05-18 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_studentinterest'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinterest',
            name='email_updates',
            field=models.BooleanField(default=False, help_text='Receive email notifications when this faculty updates their status.'),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='auto_close_hours',
            field=models.PositiveIntegerField(blank=True, default=48, help_text='Hours of inactivity before auto-closing chat threads. Null = never. Faculty only.', null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='notify_chat_closed',
            field=models.BooleanField(default=True, help_text='Email me when a chat thread is closed.'),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='notify_chat_replies',
            field=models.BooleanField(default=False, help_text='Email me on each reply in active chat threads.'),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='notify_new_chats',
            field=models.BooleanField(default=True, help_text='Email me when a new chat thread is initiated.'),
        ),
    ]
