# Generated by Django 5.1.6 on 2026-05-18 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_studentinterest_email_updates_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentinterest',
            name='email_updates',
        ),
        migrations.AddField(
            model_name='studentinterest',
            name='notify_preference',
            field=models.CharField(choices=[('all', 'All updates'), ('available', 'When available only'), ('none', 'Off')], default='none', help_text='Notification preference for this faculty status updates.', max_length=10),
        ),
    ]
