# Generated by Django 5.1.6 on 2026-05-22 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_remove_studentinterest_email_updates_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='auto_delete_closed_chats',
            field=models.BooleanField(default=False, help_text='If True, chat threads will be deleted instead of just closed when auto-closed.'),
        ),
    ]
