# Generated by Django 5.1.6 on 2026-05-22 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_facultyactivity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='auto_close_hours',
        ),
        migrations.AddField(
            model_name='userdetails',
            name='auto_close_seconds',
            field=models.PositiveIntegerField(blank=True, default=172800, help_text='Seconds of inactivity before auto-closing chat threads. Null = never. Faculty only.', null=True),
        ),
    ]
