# Generated by Django 5.1.6 on 2026-05-18 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcast', '0003_duration_option_and_until_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcastmessage',
            name='set_availability',
            field=models.CharField(blank=True, default='', help_text='When activated: "true"=Available, "false"=Unavailable, ""=no change.', max_length=10),
        ),
    ]
