# Generated by Django 5.1.6 on 2026-05-18 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('broadcast', '0004_broadcastmessage_set_availability'),
    ]

    operations = [
        migrations.RenameField(
            model_name='broadcastmessage',
            old_name='duration_minutes',
            new_name='duration_seconds',
        ),
    ]
