# Generated by Django 5.1.6 on 2026-05-17 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='set_availability',
            field=models.CharField(blank=True, default='', help_text='During event: "true"=Available, "false"=Unavailable, ""=no change.', max_length=10),
        ),
        migrations.AddField(
            model_name='quickstatustemplate',
            name='set_availability',
            field=models.CharField(blank=True, default='', help_text='When activated: "true"=Available, "false"=Unavailable, ""=no change.', max_length=10),
        ),
        migrations.AddField(
            model_name='recurringschedule',
            name='set_availability',
            field=models.CharField(blank=True, default='', help_text='When triggered: "true"=Available, "false"=Unavailable, ""=no change.', max_length=10),
        ),
    ]
