# Generated by Django 5.1.6 on 2026-05-18 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_calendarevent_set_availability_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendarevent',
            name='broadcast_message',
        ),
    ]
