# Generated by Django 5.1.6 on 2026-05-18 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_remove_calendarevent_broadcast_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recurringschedule',
            old_name='duration_minutes',
            new_name='duration_seconds',
        ),
    ]
