# Generated by Django 5.1.6 on 2026-05-22 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_rename_duration_minutes_recurringschedule_duration_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='color',
            field=models.CharField(blank=True, default='#f68b1f', max_length=20),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='set_availability',
            field=models.CharField(blank=True, default='', help_text='"true"=Available, "false"=Unavailable, ""=no change.', max_length=10),
        ),
    ]
