# Generated by Django 5.1.6 on 2026-05-22 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statussubscription',
            name='notify_preference',
            field=models.CharField(choices=[('available', 'When Available'), ('all', 'All Updates')], default='available', max_length=20),
        ),
    ]
