# Generated by Django 5.1.6 on 2026-05-18 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_directmessage_is_closed_chatthread_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatthread',
            name='deleted_by_faculty',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatthread',
            name='deleted_by_student',
            field=models.BooleanField(default=False),
        ),
    ]
