# Generated by Django 5.1.6 on 2026-05-22 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_chatthread_deleted_by_faculty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='directmessage',
            name='allows_replies',
            field=models.BooleanField(default=True),
        ),
    ]
